#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config terminal kitty

bspc monitor -d 󰝴 󰄛 󱔎  󱢴

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#7805fc"

bspc rule -a Chromium desktop='^1'
bspc rule -a Discord desktop='^2'
bspc rule -a Signal-Desktop desktop='^3'

#STARTUP
picom &
dunst &
discord &
flameshot &
signal-desktop &
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &

# Set the wallpaper
feh --bg-fill ~/Wallpapers/wallpaper1.jpeg
