#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  󰚍 󰔶 󰋘 󰮊

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#7805fc"
bspc rule -a Signal  desktop='^5'
bspc rule -a looking-glass-client desktop='^4'
#bspc rule -a League of Legends manage=off
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#STARTUP
nitrogen --restore &
picom &
dunst &
$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr &
udiskie &
#signal-desktop &
