#! /bin/sh
#USE NVIDIA ONLY
xrandr --setprovideroutputsource modesetting NVIDIA-0 &
xrandr --auto &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 󰮯 󰊠 󰮯 󰊠 󰮯

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#484848"
bspc config focused_border_color "#34ebeb"

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

dunst &
picom &
xsetroot -cursor_name left_ptr &
feh --bg-fill ~/Wallpapers/background.jpeg
$HOME/.config/polybar/launch.sh &

#STARTUP APPS
discord &
steam &
rog-control-center &
